<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

global $APPLICATION;

$APPLICATION->SetTitle("Романы");
?>
<?
//$APPLICATION->IncludeComponent(
//    "bitrix:news",
//    "bootstrap_v4",
//    [
//        'SEF_MODE' => 'Y',
//        'SEF_FOLDER' => '/romans/',
//        'SEF_URL_TEMPLATES' => [
//            'news' => '',
//            'section' => '#SECTION_CODE#',
//            'detail' => 'detail/#ELEMENT_CODE#',
//        ],
//        "ADD_ELEMENT_CHAIN" => "Y",
//        "ADD_SECTIONS_CHAIN" => "N",
//        "AJAX_MODE" => "N",
//        "AJAX_OPTION_ADDITIONAL" => "",
//        "AJAX_OPTION_HISTORY" => "N",
//        "AJAX_OPTION_JUMP" => "N",
//        "AJAX_OPTION_STYLE" => "Y",
//        "BROWSER_TITLE" => "-",
//        "CACHE_FILTER" => "N",
//        "CACHE_GROUPS" => "Y",
//        "CACHE_TIME" => "36000000",
//        "CACHE_TYPE" => "N",
//        "CHECK_DATES" => "Y",
//        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
//        "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
//        "DETAIL_DISPLAY_TOP_PAGER" => "N",
//        "DETAIL_FIELD_CODE" => ["SHOW_COUNTER", "CREATED_BY", "DATE_CREATE"],
//        "DETAIL_PAGER_SHOW_ALL" => "Y",
//        "DETAIL_PAGER_TEMPLATE" => ".default",
//        "DETAIL_PAGER_TITLE" => "Страница",
//        "DETAIL_PROPERTY_CODE" => ["UF_FILES", "UF_IMAGES"],
//        "DETAIL_SET_CANONICAL_URL" => "N",
//        "DISPLAY_BOTTOM_PAGER" => "Y",
//        "DISPLAY_DATE" => "Y",
//        "DISPLAY_NAME" => "Y",
//        "DISPLAY_PICTURE" => "Y",
//        "DISPLAY_PREVIEW_TEXT" => "Y",
//        "DISPLAY_TOP_PAGER" => "N",
//        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
//        "IBLOCK_ID" => 3,
//        "IBLOCK_TYPE" => "romans",
//        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
//        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
//        "FORUM_ID" => 1,
//        "LIST_FIELD_CODE" => [],
//        "LIST_PROPERTY_CODE" => [],
//        "MESSAGE_404" => "",
//        "META_DESCRIPTION" => "-",
//        "META_KEYWORDS" => "-",
//        "NEWS_COUNT" => "5",
//        "PAGER_BASE_LINK_ENABLE" => "N",
//        "PAGER_DESC_NUMBERING" => "N",
//        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
//        "PAGER_SHOW_ALL" => "N",
//        "PAGER_SHOW_ALWAYS" => "Y",
//        "PAGER_TEMPLATE" => ".default",
//        "PAGER_TITLE" => "Романы",
//        "PREVIEW_TRUNCATE_LEN" => "",
//        "SET_LAST_MODIFIED" => "N",
//        "SET_STATUS_404" => "N",
//        "SET_TITLE" => "N",
//        "SHOW_404" => "N",
//        "SORT_BY1" => "PROPERTY_IS_FIXED",
//        "SORT_BY2" => "ACTIVE_FROM",
//        "SORT_ORDER1" => "DESC",
//        "SORT_ORDER2" => "DESC",
//        "STRICT_SECTION_CHECK" => "N",
//        "USE_CATEGORIES" => "N",
//        "FILTER_NAME" => "",
//        "FILTER_PROPERTY_CODE" => "CATEGORY",
//        "SHOW_ALL_LINK" => "/romans/",
//        "USE_PERMISSIONS" => "N",
//        "USE_RATING" => "N",
//        "USE_REVIEW" => "N",
//        "USE_RSS" => "N",
//        "USE_SEARCH" => "N",
//        "USE_SHARE" => "N",
//    ]
//);
?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>